# Generated by Django 4.2.6 on 2023-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
