# Generated by Django 4.2.6 on 2023-11-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0004_lessons_alter_user_is_student_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='RoadReady.instructor'),
        ),
    ]
