# Generated by Django 4.2.6 on 2023-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0005_instructor_remove_user_is_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.TextField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.TextField(default=True, max_length=15),
        ),
    ]
