# Generated by Django 4.2.6 on 2023-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0006_instructor_first_name_instructor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='Lines-Yellow.png', upload_to=''),
        ),
    ]
