# Generated by Django 4.2.6 on 2023-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_image',
            field=models.FileField(default='Profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(default='Profile.png', upload_to=''),
        ),
    ]
