# Generated by Django 4.2.6 on 2023-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0009_alter_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('satisfy', models.BooleanField()),
            ],
        ),
    ]
