# Generated by Django 4.2.5 on 2023-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0011_remove_feedback_satisfy'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default='I am a driving instructor', max_length=16),
        ),
    ]
