# Generated by Django 4.2.5 on 2023-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0013_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
