# Generated by Django 4.2.5 on 2023-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0014_product_delete_carousel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
