# Generated by Django 4.2.5 on 2023-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0015_rename_lessons_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default='I am a driving instructor', max_length=200),
        ),
    ]
