# Generated by Django 4.2.5 on 2023-11-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0016_alter_instructor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='RoadReady.instructor'),
        ),
    ]
