# Generated by Django 4.2.5 on 2023-11-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0017_product_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instructor',
        ),
        migrations.AddField(
            model_name='product',
            name='instructors',
            field=models.ManyToManyField(to='RoadReady.instructor'),
        ),
    ]
