# Generated by Django 4.2.5 on 2023-11-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0021_billingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cvv',
            new_name='card_cvv',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='expiry_date',
            new_name='card_expiry',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_holder',
            new_name='card_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('paypal', 'PayPal')], default='credit', max_length=6),
        ),
    ]
