# Generated by Django 4.2.5 on 2023-11-20 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0024_alter_transaction_id_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_expiry',
            field=models.DateField(max_length=5),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transactions', models.ManyToManyField(to='RoadReady.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
