# Generated by Django 4.2.5 on 2023-11-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadReady', '0025_alter_transaction_card_expiry_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_expiry',
            field=models.DateField(null=True),
        ),
    ]
